language: node_js
node_js: node
services:
  - mongodb
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: 4e0235eb-28b7-4735-96a5-dd0874fa452f
  app: sleepy-castle-79477
  on:
    repo: preston206/peach-of-mind--backend
    branch: master
notifications:
  email:
    on_success: never
    on_failure: never